site_name: SJTU MCM Shares
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax_config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.css
nav:
  - 首页 home: index.md
  - AI工具: 
    - AI chatbot: 00_Chatbot.md
    - 学术资料搜索: 01_AI_Scholar.md
    - AI编程: 02_AI_Coding.md
    - AI写作: 02_AI_Writing.md
    - Notion AI: 03_Notion.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InuyashaYang/AI_Native_WorkFlow
      text: Star on GitHub
